CREATE DATABASE exerciciosAulas;

USE exerciciosAulas;

CREATE TABLE ALUNO(
	data_nascimento VARCHAR(10)
);

ALTER TABLE ALUNO CHANGE COLUMN data_nascimento nascimento DATE;														/* ALTERANDO O NOME DA COLUNA E O TIPO DE DADO QUE ELA ESPERA*/

ALTER TABLE ALUNO ADD COLUMN nome_aluno VARCHAR(60); 																	/* CRIANDO NOVA COLUNA DO TIPO VARCHAR PARA GUARDAR O NOME DOS ALUNOS */
ALTER TABLE ALUNO ADD CONSTRAINT pk_aluno PRIMARY KEY (nome_aluno); 													/* CRIANDO A CHAVE PRIMÁRIA DA TABELA, ONDE O REGISTRO ÚNICO DA TABELA SERÁ O NOME DO ALUNO*/
CREATE INDEX id_alunos ON ALUNO (nome_aluno(25));																		/* CRIANDO UM INDEX PARA ORDENAR OS ALUNOS E SEUS INSTRUTORES EM FUTURAS CONSULTAS, É ORDENADO OS PRIMEIROS 25 CARACTERES (POSIÇÕES) */


CREATE TABLE INSTRUTOR(
	nome_instrutor VARCHAR(60),
    email_contato VARCHAR(100),
    PRIMARY KEY (nome_instrutor)
);

CREATE TABLE CURSO(
	titulo_curso VARCHAR(30),
    curso_instrutor VARCHAR(60),
    CONSTRAINT fk_instrutor FOREIGN KEY (curso_instrutor) REFERENCES INSTRUTOR (nome_instrutor)							/* REGRA nome_regra TIPO-DA-REGRA nomeDoTipo FAZ REFERÊNCIA (AO CAMPO DA) TABELA_TAL nomeDoCampo*/
);																														/* CRIANDO UMA CHAVE ESTRANGEIRA POIS UM CURSO PRECISA SER MINISTRADO POR PELO MENOS UM INSTRUTOR */			

CREATE INDEX cursosEinstrutores ON CURSO (curso_instrutor(40));															/* CRIANDO UM INDEX PARA ORDENAR OS CURSOS E SEUS INSTRUTORES EM FUTURAS CONSULTAS, É ORDENADO OS PRIMEIROS 40 CARACTERES (POSIÇÕES) */

ALTER TABLE INSTRUTOR DROP COLUMN email_contato;																		/* ELIMINANDO A COLUNA EMAIL_CONTATO DA TABELA INSTRUTOR */

INSERT INTO ALUNO (nome_aluno) VALUES ('Caíque Rodrigues');																/* INSERINDO UM NOVO REGISTRO NO CAMPO nome_aluno */
SELECT nome_aluno FROM ALUNO;																							/* CONSULTANDO O CAMPO nome_aluno DA TABELA ALUNO*/

INSERT INTO ALUNO (nascimento, nome_aluno) VALUES ("2019-09-16", 'Elena Carvalho');										/* INSERINDO DOIS NOVOS REGISTROS EM CAMPOS DIFERENTES, DATA FORMATO YYYY-MM-DD */
SELECT nome_aluno, nascimento FROM ALUNO;
SELECT * FROM ALUNO;

INSERT INTO INSTRUTOR VALUES ('Vilmara Silva');
SELECT * FROM INSTRUTOR;

INSERT INTO CURSO VALUES ('ANÁLISE E DSVT DE SISTEMAS', 'Vilmara Silva');
SELECT * FROM CURSO;

INSERT INTO CURSO VALUES ('SISTEMAS DA INFORMAÇÃO', 'Vilmara Silva');
SELECT * FROM CURSO;

SELECT nascimento FROM ALUNO WHERE nome_aluno = 'Elena Carvalho';														/* CONSULTANDO UM VALOR DE CAMPO DE ACORDO COM UMA CONDIÇÃO - O NOME DO ALUNO - */
UPDATE ALUNO SET nascimento = "2004-07-08" WHERE nome_aluno = 'Caíque Rodrigues';										/* ATUALIZANDO UM REGISTRO DE ACORDO COM UMA CONDIÇÃO - O NOME DO ALUNO - */
SELECT * FROM ALUNO;

DELETE FROM CURSO WHERE titulo_curso = 'ANÁLISE E DSVT DE SISTEMAS' AND curso_instrutor = 'Vilmara Silva';				/* APAGANDO UM REGISTRO DE ACORDO COM UMA CONDIÇÃO - TITULO DO CURSO E INSTRUTOR - */
SELECT * FROM CURSO;


DELETE FROM CURSO WHERE titulo_curso = 'SISTEMAS DA INFORMAÇÃO' AND curso_instrutor = 'Vilmara Silva';

INSERT INTO CURSO VALUES ('ANÁLISE E DSVT DE SISTEMAS', 'Vilmara Silva');

INSERT INTO CURSO VALUES ('SISTEMAS DA INFORMAÇÃO', 'Vilmara Silva');

SELECT * FROM CURSO;

ALTER TABLE instrutor ADD COLUMN data_matricula DATE;																	/* ADICIONANDO UMA NOVA COLUNA NA TABELA INSTRUTOR */
UPDATE INSTRUTOR SET data_matricula = "2023-05-16" WHERE nome_instrutor = 'Vilmara Silva'; 

SELECT nome_aluno FROM ALUNO WHERE nascimento < "2003-05-12"; 

SELECT * FROM ALUNO UNION SELECT * FROM CURSO;																			/* UNINDO CONSULTAS DE DUAS TABELAS DIFERENTES, AQUI VALORES DUPLICADOS NÃO SÃO DISPONIBILIZADOS */
SELECT * FROM ALUNO UNION ALL SELECT * FROM CURSO;																		/* AQUI OS VALORES DUPLICADOS SÃO CONSULTADOS NORMALMENTE */


/* TESTANDO O AUTO_INCREMENT */

CREATE TABLE TESTE(
	id_ INT NOT NULL AUTO_INCREMENT,
    salario FLOAT NOT NULL,
    cidade VARCHAR(40) NOT NULL,
    PRIMARY KEY(id_)
);

INSERT INTO TESTE (salario, cidade) VALUES (2.900, 'EMBU DAS ARTES');
SELECT salario FROM TESTE;
SELECT * FROM TESTE;

INSERT INTO TESTE (salario, cidade) VALUES (round(2.900, 4), 'EMBU DAS ARTES');
INSERT INTO TESTE (salario, cidade) VALUES (2.434, 'TABOAO DA SERRA');
INSERT INTO TESTE (salario, cidade) VALUES (1.234, 'COTIA');