CREATE DATABASE CADASTRO
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE CADASTRO;

CREATE TABLE PESSOAS(
	ID_ INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
    NASCIMENTO DATE,
    SEXO ENUM('Masculino', 'Feminino'),
    PESO DECIMAL(5,2),
    ALTURA DECIMAL(3,2),
    NACIONALIDADE VARCHAR(20) DEFAULT 'Brasil',
	PRIMARY KEY (ID_)
    
) DEFAULT CHARSET = utf8;

INSERT INTO PESSOAS (NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE) VALUES ('Elena Carvalho', "2019-09-16", 'Feminino', 23.4, 1.0, 'Brasil');
INSERT INTO PESSOAS (NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE) VALUES ('Caíque Rodrigues', "2004-07-08", 'Masculino', 60.0, 1.70, 'Brasil');
INSERT INTO PESSOAS (NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE) VALUES ('Michael Scott', "1988-10-12", 'Masculino', 70.15, 1.75, 'EUA');
INSERT INTO PESSOAS (NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE) VALUES ('Pam Beasly', "1995-05-02", 'Feminino', 60.0, 1.65, 'EUA');
INSERT INTO PESSOAS (NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE) VALUES ('Chandler Bing', "1995-02-14", 'Masculino', 75.0, 1.76, 'EUA');
INSERT INTO PESSOAS (NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE) VALUES ('Rachel Green', "1995-09-23", 'Feminino', 56.0, 1.60, 'EUA');


INSERT INTO PESSOAS (NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE) VALUES ('Monica', "2005-01-01", 'Feminino', 25.0, 1.25,'Brasil'),
('Cascão', "2005-03-16", 'Masculino', 22.0, 1.25,'Brasil'),
('Cebolinha', "2005-06-20", 'Masculino', 23.0, 1.25,'Brasil'),
('Magali', "2005-08-07", 'Feminino', 22.0, 1.25,'Brasil');

SELECT * FROM PESSOAS;

/* PARA APAGAR COLUNAS ONDE EXISTE CHAVE PRIMÁRIA, USAMOS O DELETE NA COLUNA COM CHAVE EM QUESTÃO: */

DELETE FROM PESSOAS WHERE (ID_ = '11');			/* REMOVENDO VALORES DUPLICADOS */
DELETE FROM PESSOAS WHERE (ID_ = '12');
DELETE FROM PESSOAS WHERE (ID_ = '13');
DELETE FROM PESSOAS WHERE (ID_ = '14');
DELETE FROM PESSOAS WHERE (ID_ = '15');
DELETE FROM PESSOAS WHERE (ID_ = '16');
DELETE FROM PESSOAS WHERE (ID_ = '17');
DELETE FROM PESSOAS WHERE (ID_ = '18');
DELETE FROM PESSOAS WHERE (ID_ = '19');
DELETE FROM PESSOAS WHERE (ID_ = '20');
DELETE FROM PESSOAS WHERE (ID_ = '21');
DELETE FROM PESSOAS WHERE (ID_ = '22');

ALTER TABLE PESSOAS ADD COLUMN PROFISSAO VARCHAR(10);
DESC PESSOAS;

ALTER TABLE PESSOAS DROP COLUMN PROFISSAO;

ALTER TABLE PESSOAS ADD COLUMN PROFISSAO VARCHAR(10) AFTER NOME;
ALTER TABLE PESSOAS ADD CODIGO INT FIRST;
ALTER TABLE PESSOAS MODIFY COLUMN PROFISSAO VARCHAR(20) DEFAULT '';  /* ALTERANDO O TIPO PRIMITIVO DE DADO DA COLUNA, COMANDO MODIFY. */
ALTER TABLE PESSOAS CHANGE PROFISSAO PROF VARCHAR(20) DEFAULT '';    /* ALTERANDO O NOME DA COLUNA USANDO O COMANDO CHANGE. TAMBÉM É POSSÍVEL MUDAR AS CONSTRAINTS. */
ALTER TABLE PESSOAS RENAME TO PESSOAS__;							 /* RENOMEANDO O NOME DA TABELA */

DESC PESSOAS__;

CREATE TABLE IF NOT EXISTS GAFANHOTOS (TESTE INT);					 /* CRIANDO UMA TABELA APENAS SE ELA NÃO EXISTIR */

CREATE TABLE IF NOT EXISTS CURSOS(		
	NOME VARCHAR(30) NOT NULL UNIQUE,
    DESCRICAO TEXT,
    CARGA INT UNSIGNED,
    TOTAULAS INT UNSIGNED,
    ANO YEAR DEFAULT '2016'
);

DESC CURSOS;

ALTER TABLE CURSOS ADD COLUMN IDCURSO INT FIRST;
ALTER TABLE CURSOS ADD PRIMARY KEY (IDCURSO);

DROP TABLE IF EXISTS CURSOS;										/* APAGANDO A TABELA INTEIRA */
